[package]
name = "vanihash"
version = "0.0.1"
published-at = "0x0"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
vanihash = "0x0"
